
name: plastic_marg
description: Plastic Marg Flutter app

publish_to: 'none' # since this is not published on pub.dev

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.7.0
  firebase_auth: ^4.2.5
  cloud_firestore: ^4.4.5
  google_sign_in: ^6.1.0
  razorpay_flutter: ^1.3.7

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
